FROM node:16.19.1-alpine3.17

# For development add /bin/bash
RUN apk update && apk add bash

# Set up the server directory
WORKDIR /app
COPY . /app
RUN mkdir -p /app/dx.backend

# Install yarn dependencies
RUN yarn install
RUN yarn build

# Run `yarn docker` to build, migrate and run the server with pm2.
CMD ["yarn", "dev"]
