FROM node:16.19.1-alpine3.17

# For development add /bin/bash
RUN apk update && apk add bash

# Set up the server directory
WORKDIR /app
COPY . /app

RUN mkdir -p /app/dx.backend
# Ensure .env is available for the execSync index of the chart rendering
RUN echo "PARSED_DATA_FILES_PATH='/app/dx.backend/parsed-data-files/'" > .env

# Install yarn dependencies
RUN yarn install --network-timeout 100000
RUN yarn build
RUN npm install -g webpack webpack-cli
RUN yarn initialise-server

# Run `yarn docker` to build, migrate and run the server with pm2.
CMD ["yarn", "dev"]
